#!/bin/bash
# dmenu2 on AUR using i3-dmenu-desktop --dmenu option
# dmenu_run -nb "#1f222d" -sb "#1f222d" -sf "#7780a1" -fn "Noto Sans-12"  -b -h 25 -x 129 -y 1 -w 730
# 
# with short workspaces (e.g just <1: icon>, <2: icon> etc)
# dmenu_run -nb "#1f222d" -sb "#D5D5D5" -sf "#1f222d" -fn "Noto Sans-12"  -b -h 24 -x 170 -y 1 -w 600
# 
# with long workspaces
dmenu_run -nb "#1f222d" -sb "#D5D5D5" -sf "#1f222d" -fn "Noto Sans-12"  -b -h 24 -x 220 -y 1 -w 550
