#!/bin/bash
#
# Mounting $1 (default: /dev/sdb) device
# to $2 (default: /home/charlike/usbstick)
# 

device=${1:-"/dev/sdb"}
usbstick=${2:-"/home/charlike/usbstick"}

sudo mount "$device" "$usbstick" -o umask=000
